### ISSUE TITLE
no gen/ directory commited

### ISSUE THREAD

**Issue by jackgu1988** [evozi/DroidSniff#3]
There is no gen/ directory, therefore no R.java, without which it is imposible to work on the code. I wanted to fix a bug where when you are browsing a site using a sniffed cookie and hit back the application exits.

**Comment by vboss1161** [comment]
but where is your full code project which you are doing?

**Comment by jackgu1988** [comment]
What do you mean?

**Comment by vboss1161** [comment]
yes, I mean can you tell me the link lead to your code project. sorry because I am newbie, I try to read all help tutorial but it's hard to find.
